backend/portfolio/__init__.py
import os
from flask import Flask

app = Flask(__name__)

from dotenv import load_dotenv  # <-- Load .env file
# Load environment variables from .env
load_dotenv()

app.secret_key = os.getenv('SECRET_KEY')

from portfolio.core.views import core
from portfolio.error_pages.handlers import error_pages
app.register_blueprint(error_pages)
app.register_blueprint(core)

backend/portfolio/core/views.py
# portfolio/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
   user = {"name": "Nico"}
   return render_template("index.html", user=user)

backend/portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ user.name }} | Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <link rel="icon" href="{{ url_for('static', filename='images/Robot.png') }}" type="image/png">
</head>
<body data-bs-theme="dark" class="bg-black text-light">
    <nav class="navbar navbar-expand-lg fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <!-- <img src="{{ url_for('static', filename='images/Robot.png') }}" alt="Logo" class="d-inline-block align-text-top"> -->
      Nicolas Cava
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0 contact-nav">
        <!-- <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('core.index') }}">Home</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link active contact-link" href="#contact">Lets Connect!</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


    {% block content %}

    {% endblock %}

    <!-- <nav class="navbar navbar-dark bg-dark border-top border-secondary fixed-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Add Item</a>
    <a class="navbar-brand" href="#">Add Category</a>
  </div>
</nav> -->

    <!-- Your React bundle (we'll generate backend/static/js/main.js) -->
    <script type="module" src="{{ url_for('static', filename='react/js/main.js') }}"></script>
</body>
</html>

backend/portfolio/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div id="react-root" data-username="{{ user.name }}"></div>
{% endblock %}